messages:
  commands:
    start:
      text: 'start'
      description: 'Команда для старта бота, можно использовать в любой части текста'
    binance_start:
      text: 'binance'
      description: 'Команда для старта бота, можно использовать в любой части текста'
    unknown_command: 'Я не знаю такой команды'
  errors:
    default: 'это дефолтная ошибка'
    unauthorized: 'Ты не авторизован не на одной из криптобирж'
    one_crypto_error: 'Ошибка в получении данных о этой криптовалюте'
