message:
  commands:
    start: 'Привет! Я бот для криптовалют. ТЫ можешь выбрать из 2 криптобиржи и ее услуги'
    binance_start: 'Это команда для бинанса'
    unknown_command: 'Я не знаю такой команды'
  errors:
    default: 'это дефолтная ошибка'
    unauthorized: 'Ты не авторизован не на одной из криптобирж'
